### PR TITLE
Add elapsed_time field to VisionResult message.

### PR DESCRIPTION
**Pull request by arhuaco**
Maciek: Please check. This is for the discussion we had yesterday about measuring performance. Does it make sense?

Note: I didn't check that the change compiles. We need to fix CMakeLists.txt.

### CODE REVIEW

**Comment by maciekrb** [comment]
It makes me think how can we use this to effectively monitor the requests. This field allows us to measure request latency, but for this to be effective, we need to place a proxy in between that would   monitor every incoming message to the detection-server and report somewhere. 

The alternative option would be to generate log entries to a file or the `stdout` where we can add the processing time as well.  As of current configuration, we already receive such messages in Google's logging facilities, it is easy to write the logs to BigQuery as well, and have some stats available based on the logs. 

I'm up for both solutions, I just see the second easier to implement. This may be because I'm unaware of disadvantages of writing to stdout / stderr in the detection server

**Comment by eighteyes** [comment]
+1 bump

**Comment by eighteyes** [comment]
+1 Bump

**Comment by brianofrokk3r** [comment]
@arhuaco @maciekrb is this still relevant?

**Comment by arhuaco** [comment]
No. Closing. This is trivial to add when we implement this.

**Comment by brianofrokk3r** [comment]
This ties to Dwell Time and Session Time of the Tracker? @arhuaco

**Comment by arhuaco** [comment]
Nope. That's already working well. That will come out with this week's release.

**Pull request closed without merging**
